builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  ignore:
    - goos: darwin
      goarch: 386
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
brews:
- tap:
    owner: toshimaru
    name: homebrew-nyan
  description: Colored cat command which supports syntax highlighting. 
  homepage: https://github.com/toshimaru/nyan
  license: MIT
  test: |
    system "#{bin}/nyan -v"
